version: "3.1"
services:
    www:
        build: .
        ports: 
            - "80:80"
            - "443:443"
            - "8090:8090"
            - "8091:8091"
        volumes:
            - ./htdocs/:/var/www/html/
        links:
            - db
        depends_on:
            - db
        networks:
            - default
        restart: always
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: app-ll
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
        # avoid db issue db_1          | mbind: Operation not permitted
        security_opt:
             - seccomp:unconfined
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        depends_on:
            - db
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        restart: always
    redis:
        image: 'redis:alpine'
        ports:
            - 6379:6379
        networks:
            - default
        restart: always
volumes:
    persistent:
